import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#bde9ff",
        "on-secondary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "secondary-container": "#e2dfde",
        "on-secondary-fixed-variant": "#474746",
        "surface-container-low": "#f3f3f3",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container": "#eeeeee",
        "background": "#f9f9f9",
        "on-tertiary-container": "#606264",
        "on-error": "#ffffff",
        "on-surface": "#1a1c1c",
        "primary-container": "#b9e5fb",
        "surface-tint": "#396476",
        "surface": "#f9f9f9",
        "inverse-primary": "#a1cde2",
        "on-tertiary": "#ffffff",
        "tertiary": "#5d5e60",
        "surface-container-high": "#e8e8e8",
        "tertiary-fixed": "#e2e2e4",
        "primary": "#396476",
        "teal-primary": "#00897B",
        "blue-primary": "#1E88E5",
        "on-secondary-fixed": "#1c1b1b",
        "surface-dim": "#dadada",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001f2a",
        "surface-variant": "#e2e2e2",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a1cde2",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-fixed-variant": "#454749",
        "on-background": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#1e4c5e",
        "secondary": "#5f5e5e",
        "secondary-fixed": "#e5e2e1",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#1a1c1d",
        "on-primary-container": "#3c677a",
        "inverse-on-surface": "#f1f1f1",
        "tertiary-container": "#dedee0",
        "on-secondary-container": "#636262",
        "error": "#ba1a1a",
        "on-surface-variant": "#41484c",
        "outline": "#71787c",
        "tertiary-fixed-dim": "#c6c6c8",
        "outline-variant": "#c1c7cc",
        "inverse-surface": "#2f3131",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "120px",
        "container-max": "1440px",
        gutter: "24px",
        unit: "8px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-manrope)", "sans-serif"],
        "mono-label": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-manrope)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-manrope)", "sans-serif"],
        "display-xl": ["var(--font-manrope)", "sans-serif"],
        "label-caps": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["20px", { lineHeight: "160%", fontWeight: "400" }],
        "headline-lg": ["64px", { lineHeight: "120%", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-label": ["13px", { lineHeight: "100%", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "160%", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "130%", fontWeight: "600" }],
        "headline-lg-mobile": ["40px", { lineHeight: "120%", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-xl": ["120px", { lineHeight: "110%", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "100%", letterSpacing: "0.1em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
